@url = http://localhost:3000/material
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Ik9tbmF0aCBTaGluZGUiLCJ1c2VybmFtZSI6Im9tbmF0aCIsInJvbGVJZCI6MSwic2l0ZUlkIjoxLCJlbXBsb3llZUlkIjoiMTEiLCJpYXQiOjE3ODE4MzQxNDZ9.l3BhhfD0bthvdMgjHGR0VCSqXnWCDTlQI8DLsOhV7Nw

### Get all materials
GET {{url}}?status=1&inStock=0
Authorization: {{token}}
Content-Type: application/json


###


### Get all materials
GET {{url}}/search/records?
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific material by ID
GET {{url}}/1
Authorization: {{token}}
Content-Type: application/json


###


### Create a new material
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "madf",
  "description": "asdf",
  "customerName": "asdf",
  "UOM": "QEDF",
  "netWeight": "ADF",
  "netVolume": "AD",
  "siteId": 2
}

{
  "siteId": 7,
  "name": "PrinDDter1",
  "description": "Printer",
  "customerName": "Infosys Tech",
  "UOM": "kg",
  "netVolume": 1.2
}
,

###


### Update a material
# Any you want update can be accepted
PUT {{url}}/12
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Update invt",
  "description": "mouse",
  "customerName": "Infosys Tech",
  "UOM": "kg"
}


###


### Delete a material
DELETE {{url}}/118
Authorization: {{token}}
Content-Type: application/json


### Restore a material
PATCH  {{url}}/118
Authorization: {{token}}
Content-Type: application/json


### Create Bulk materials
POST {{url}}/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  {
    "name": "Copper Wire",
    "descripiton": "Reliance",
    "UOM": "Kg",
    "quantity": 200,
    "netVolume": 1000,
    "customerName": "ABC Constructions"
  },
  {
    "name": "Steel Rod 6mm",
    "descripiton": "Tata Steel",
    "UOM": "Kg",
    "quantity": 150,
    "netVolume": 750,
    "customerName": "XYZ Builders"
  }
]
