@url = http://localhost:3000/role
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVJZCI6MSwic2l0ZUlkIjpudWxsLCJlbXBsb3llZUlkIjoiMSIsImlhdCI6MTc4MTgzMTYzOX0.hwLD6PCuekVF4NQWAqboGA-oZJ4ub4fTy8ZeqQNjR8A

### Get all roles
GET {{url}}?status=1
Authorization: {{token}}
Content-Type: application/json


###


### Get all roles
GET {{url}}/search/records?status=-0&offset=0&limit=100&name=
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific role by ID
GET {{url}}/1
Authorization: {{token}}
Content-Type: application/json


###


### Create a new role
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Manger"
}


###


### Update a role
PUT {{url}}/3
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Pritam"
}


###


### Delete a role
DELETE {{url}}/2
Authorization: {{token}}
Content-Type: application/json


###


### Create Bulk Users
POST {{url}}/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  {
    "name": "Suppervisor"
  },
  {
    "name": "Picker"
  },
  {
    "name": "Manager"
  },
  {
    "name": "Auditor"
  }
]
