@url = http://localhost:7000
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6Ik9tbmF0aCBTaGluZGUiLCJ1c2VybmFtZSI6Im9tbmF0aCIsInJvbGVJZCI6Miwic2l0ZUlkIjoxLCJlbXBsb3llZUlkIjoiMTIzMzIiLCJpYXQiOjE3NjE2Mzk5MzN9.3_XamDTQQbangJh6TY5mzF7EeE1iuiyVQXqRMnrnLGQ

### Get all shelfs
GET {{url}}/shelf?status=1&
Authorization: {{token}}
Content-Type: application/json


###


### Get all shelfs
GET {{url}}/shelf/search/records?offset=0&limit=100&siteId=2
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific shelf by ID
GET {{url}}/shelf/1
Authorization: {{token}}
Content-Type: application/json


###


### Create a new shelf
POST {{url}}/shelf
Authorization: {{token}}
Content-Type: application/json

{
  "rackId": 6,
  "name": "shelf4"
}


###


### Update a shelf
PUT {{url}}/shelf/1
Authorization: {{token}}
Content-Type: application/json

{
  "rackId": 1,
  "name": "Pune"
}


###


### Delete a shelf
DELETE {{url}}/shelf/1
Authorization: {{token}}
Content-Type: application/json


###


### Create Bulk Users
POST {{url}}/shelf/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  {
    "rackId": 6,
    "name": "Suppervisor"
  },
  {
    "rackId": 6,
    "name": "Tester"
  },
  {
    "rackId": 6,
    "name": "QA Analyst"
  }
]

#
[
  { "siteName": "Pune", "zoneName": "Supervisor", "rackName": "Rack1", "shelfName": "ShelfA" },
  { "siteName": "Pune", "zoneName": "Supervisor", "rackName": "Rack1", "shelfName": "ShelfB" }
]
