@url = http://localhost:3000/shelf
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVJZCI6MSwic2l0ZUlkIjpudWxsLCJlbXBsb3llZUlkIjoiMSIsImlhdCI6MTc3OTg3NjY1OH0.wFv1cd2E54_4Wbw4MEJobZ17XI1kmv2hmworeuOOUZ4

### Get all shelfs
GET {{url}}?
Authorization: {{token}}
Content-Type: application/json


###


### Get all shelfs
GET {{url}}/search/records?limit=5&offset=0&status=0
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific shelf by ID
GET {{url}}/1
Authorization: {{token}}
Content-Type: application/json


###


### Create a new shelf
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
  "rackId": 6,
  "name": "shelf4"
}


###


### Update a shelf
PUT {{url}}/1
Authorization: {{token}}
Content-Type: application/json

{
  "rackId": 1,
  "name": "Pune"
}


###


### Delete a shelf
DELETE {{url}}/1
Authorization: {{token}}
Content-Type: application/json


### Restore a shelf
DELETE {{url}}/1
Authorization: {{token}}
Content-Type: application/json


###


### Create Bulk Users
POST {{url}}/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  {
    "siteName": "Pune",
    "zoneName": "A-Zone",
    "rackName": "R1",
    "shelfName": "S1"
  },
  {
    "siteName": "Pune",
    "zoneName": "A-Zone",
    "rackName": "R1",
    "shelfName": "S2"
  },
  {
    "siteName": "Pune",
    "zoneName": "A-Zone",
    "rackName": "R2-A-Pune",
    "shelfName": "S3"
  }
]
