@url = http://localhost:3000
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVJZCI6MSwic2l0ZUlkIjpudWxsLCJlbXBsb3llZUlkIjoiMSIsImlhdCI6MTc4MTgzMTYzOX0.hwLD6PCuekVF4NQWAqboGA-oZJ4ub4fTy8ZeqQNjR8A

### Get all users
GET {{url}}/user?status=0
Authorization: {{token}}
Content-Type: application/json


###


### Get all users
GET {{url}}/user/search/records
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific user by ID
GET {{url}}/user/1
Authorization: {{token}}
Content-Type: application/json


###


### Create a new user
POST {{url}}/user
Authorization: {{token}}
Content-Type: application/json

{
  "name": "Omn Shinde",
  "username": "omnath3",
  "password": "12345",
  "employeeId": "2236",
  "roleId": 2,
  "siteId": null
}


###


### Update a user
PUT {{url}}/user/47
Authorization: {{token}}
Content-Type: application/json

{
  "username": "omnath12",
  "password": "12345",
  "siteId": 1
}


###


### Delete a user
DELETE {{url}}/user/
Authorization: {{token}}
Content-Type: application/json


###


### Create Bulk Users
POST {{url}}/user/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  {
    "siteId": 1,
    "roleId": 1,
    "employeeId": 11,
    "username": "omnath",
    "password": "12345"
  },
  {
    "siteId": 2,
    "roleId": 2,
    "employeeId": 12,
    "username": "shubham",
    "password": "12345"
  },
  {
    "siteId": 3,
    "roleId": 3,
    "employeeId": 14,
    "username": "yug",
    "password": "12345"
  },
  {
    "siteId": 4,
    "roleId": 4,
    "employeeId": 13,
    "username": "sachin",
    "password": "12345"
  },
  {
    "siteId": 1,
    "roleId": 4,
    "employeeId": 16,
    "username": "ganesh",
    "password": "12345"
  }
]
