@url = http://localhost:3000/zone
@token = JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkFkbWluIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVJZCI6MSwic2l0ZUlkIjpudWxsLCJlbXBsb3llZUlkIjoiMSIsImlhdCI6MTc4MTgzMTYzOX0.hwLD6PCuekVF4NQWAqboGA-oZJ4ub4fTy8ZeqQNjR8A

### Get all zones
GET {{url}}?status=0
Authorization: {{token}}
Content-Type: application/json


###


### Get all zones
GET {{url}}/search/records
Authorization: {{token}}
Content-Type: application/json


###


### Get a specific zone by ID
GET {{url}}/6
Authorization: {{token}}
Content-Type: application/json


###


### Create a new zone
POST {{url}}
Authorization: {{token}}
Content-Type: application/json

{
  "siteId": 1,
  "name": "Balewadi322"
}


###


### Update a zone
PUT {{url}}/1
Authorization: {{token}}
Content-Type: application/json

{
  "siteId": 2,
  "name": "Pune"
}


###


### Delete a zone
DELETE {{url}}/6
Authorization: {{token}}
Content-Type: application/json


### Restore a zone
PATCH  {{url}}/2
Authorization: {{token}}
Content-Type: application/json


###


### Create Bulk Users
POST {{url}}/bulk-records
Authorization: {{token}}
Content-Type: application/json

[
  { "siteName": "Pune", "zoneName": "A-Zone" },
  { "siteName": "Mumbai", "zoneName": "B-Zone" },
  { "siteName": "Nagpur", "zoneName": "C-Zone" },
  { "siteName": "Chhatrapati Sambhajinagar", "zoneName": "D-Zone" }
]
